version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab.local.jarand.site'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.local.jarand.site'
        registry_external_url 'http://gitlab.dockerhost.home:5000'

        gitlab_rails['registry_enabled'] = true
        gitlab_rails['registry_host'] = "gitlab.dockerhost.home:5000"
        gitlab_rails['registry_api_url'] = "http://registry:5000"
        gitlab_rails['registry_path'] = "/var/opt/gitlab/gitlab-rails/shared/registry"
        gitlab_rails['registry_issuer'] = "omnibus-gitlab-issuer"
        registry['enable'] = true
        registry['username'] = "registry"
        registry['group'] = "registry"
        registry['log_directory'] = "/var/log/gitlab/registry"

        gitlab_rails['gitlab_shell_ssh_port'] = 2424

        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.gmail.com"
        gitlab_rails['smtp_user_name'] = ""
        gitlab_rails['smtp_password'] = ""
        gitlab_rails['smtp_domain'] = "smtp.gmail.com"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['gitlab_email_from'] = 'mail@jarand.site'
        gitlab_rails['gitlab_email_reply_to'] = '

        gitlab_rails['omniauth_enabled'] = true
        gitlab_rails['omniauth_allow_single_sign_on'] = ['saml']
        gitlab_rails['omniauth_sync_email_from_provider'] = 'saml'
        gitlab_rails['omniauth_sync_profile_from_provider'] = ['saml']
        gitlab_rails['omniauth_sync_profile_attributes'] = ['email']
        #gitlab_rails['omniauth_auto_sign_in_with_provider'] = 'saml'
        gitlab_rails['omniauth_block_auto_created_users'] = false
        gitlab_rails['omniauth_auto_link_saml_user'] = true
        gitlab_rails['omniauth_providers'] = [
          {
            name: "saml",
            label: "authentik", # Optional label for login button, defaults to "Saml"
            # ---- This tells GitLab OmniAuth which attribute has the groups ----
            groups_attribute: 'http://schemas.xmlsoap.org/claims/Group',
            # ---- This tells which group to assign users admin permissions -----
            admin_groups: ['app-gitlab-admin'],
            args: {
              assertion_consumer_service_url: "",
              idp_cert_fingerprint: "",
              idp_sso_target_url: "",
              issuer: "",
              name_identifier_format: "",
              attribute_statements: {
                email: ['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress'],
                first_name: ['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name'],
                nickname: ['http://schemas.goauthentik.io/2021/02/saml/username'],
                Groups: ['http://schemas.xmlsoap.org/claims/Group']
              }
            }
          }
        ]
    ports:
      - '443:443'
      - '2424:22'
    volumes:
      - './data/config:/etc/gitlab'
      - './data/logs:/var/log/gitlab'
      - './data/data:/var/opt/gitlab'
    shm_size: '256m'

  registry:
    image: registry:2
    container_name: registry
    restart: always
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
    ports:
      - '5000:5000'
    volumes:
      - './registry:/var/lib/registry'
      - './data/logs:/var/log/gitlab'
      - './data/data:/var/opt/gitlab'
    shm_size: '256m'

  registry:
    image: registry:2
    container_name: registry
    restart: always
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
    ports:
      - '5000:5000'
    volumes:
      - './registry:/var/lib/registry'